# Do NOT update manually; changes here will be overwritten by Copier
_commit: 00cee12
_src_path: https://github.com/ingadhoc/addons-repo-template.git
description: Modules that extend odoo for common needs of ADHOC Customers
is_private: false
name: argentina-sale
odoo_version: 18.0
pre_commit_ignore: []
slug: ''

